// <auto-generated />
using EF2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260505110801_addUsers")]
    partial class addUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF2.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Henderson",
                            Price = 45.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Marlowe",
                            Price = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlie Day",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diana Prince",
                            Price = 550.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Edward Nigma",
                            Price = 75.25m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fiona Gallagher",
                            Price = 21.00m
                        },
                        new
                        {
                            Id = 7,
                            Name = "George Bluth",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hannah Abbott",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ian Curtis",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Julia Child",
                            Price = 125.75m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
