// <auto-generated />
using MVC_PROJECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_PROJECT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613113831_AddProductImages")]
    partial class AddProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_PROJECT.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobiles"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptops"
                        });
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Latest iPhone model",
                            Name = "iPhone 13",
                            Price = 999.99m,
                            Quantity = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Flagship Samsung phone",
                            Name = "Samsung Galaxy S21",
                            Price = 899.99m,
                            Quantity = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "High-end tablet from Apple",
                            Name = "iPad Pro",
                            Price = 799.99m,
                            Quantity = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Versatile 2-in-1 device",
                            Name = "Microsoft Surface Pro",
                            Price = 999.99m,
                            Quantity = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Powerful laptop from Apple",
                            Name = "MacBook Pro",
                            Price = 1299.99m,
                            Quantity = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Compact and powerful laptop",
                            Name = "Dell XPS 13",
                            Price = 1099.99m,
                            Quantity = 0,
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("MVC_PROJECT.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImage");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Product", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.ProductImage", b =>
                {
                    b.HasOne("MVC_PROJECT.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MVC_PROJECT.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
